sonar.projectKey=lucasgomesdacruz_BPO
sonar.organization=sonar.organization=lucasgomesdacruz

sonar.sources=src
sonar.exclusions=node_modules/**,.next/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info
